export interface SpeciesData {
  sapwood: string[];
  heartwood: string[];
  colorStreaksOrSpots: string[];
  colorVariation: string[];
  sharpColorContrastsAtJoints: string[];
  bookMatched: string[];
  slipMatched: string[];
  pleasingMatched: string[];
  plainS: string[];
  quarRift: string[];
  rotary: string[];
  smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: string[];
  conspicuousBurlsMaxSize: string[];
  avgNumber: string[];
  maxSize: string[];
  darkPartTotal: string[];
  combinedAvgNumber: string[];
  maxSizeSounds: string[];
  maxSizeRepaired: string[];
  avgNoRepaired: string[];
  mineralStreaks: string[];
  barkPockets: string[];
  wormTracks: string[];
  vineMarks: string[];
  crossBars: string[];
  roughCutRupturedGrain: string[];
  blendedRepairedTaperingHairlineSplits: string[];
  repairs: string[];
  gumSpots: string[];
  quartered: string[];
}

export interface Grades {
  AA?: SpeciesData;
  A?: SpeciesData;
  B?: SpeciesData;
  C?: SpeciesData;
  D?: SpeciesData;
}

export interface Data {
  cherry: Grades;
  maple: Grades;
  birch: Grades;
  white_oak: Grades;
  oak: Grades;
  walnut: Grades;
  ceder: Grades;
  pine: Grades;
  redwood: Grades;
  fir: Grades;
}
export const data: Data = {
  cherry: {
    AA: {
      sapwood: ["No"],
      heartwood: ["Yes"],
      colorStreaksOrSpots: ["Slight"],
      colorVariation: ["Slight"],
      sharpColorContrastsAtJoints: ["Yes if Slip, Plank or Random matched	"],
      bookMatched: ["Yes"],
      slipMatched: ["Specify"],
      pleasingMatched: ["--"],
      plainS: ["6 in."],
      quarRift: ["3 in."],
      rotary: ["6 in."],
      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: [
        "1 per 4 sq ft 32 per 4 ft x 8 ft panel",
      ],
      conspicuousBurlsMaxSize: ["1/4 in."],
      avgNumber: ["1 per 5 sq ft 6 per 4 x 8 ft"],
      maxSize: ["1/8 in."],
      darkPartTotal: ["1/4 in."],
      combinedAvgNumber: ["No"],
      maxSizeSounds: ["No"],
      maxSizeRepaired: ["No"],
      avgNoRepaired: ["No"],
      mineralStreaks: ["Slight"],
      barkPockets: ["No"],
      wormTracks: ["No"],
      vineMarks: ["Slight"],
      crossBars: ["Slight"],
      roughCutRupturedGrain: ["No	"],
      blendedRepairedTaperingHairlineSplits: [
        " Two 1/32 in. x 3 in. on panel ends only",
      ],
      repairs: ["Very Small Blending"],
      gumSpots: ["Occasional Gum spots in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    A: {
      sapwood: [" No^a"],
      heartwood: ["Yes"],
      colorStreaksOrSpots: ["Slight"],
      colorVariation: ["Slight"],
      sharpColorContrastsAtJoints: ["Yes if Slip, Plank or Random matched	"],
      bookMatched: ["Yes"],
      slipMatched: ["Specify"],
      pleasingMatched: ["--"],
      plainS: ["5 in."],
      quarRift: ["3 in."],
      rotary: ["5 in."],
      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: [
        "1 per 1 1/3 sq ft 24 per 4 ft x 8 ft panel",
      ],
      conspicuousBurlsMaxSize: ["3/8 in."],
      avgNumber: ["1 per 2 sq ft 16 per 4 x 8 ft"],
      maxSize: ["1/8 in."],
      darkPartTotal: ["1/4 in."],
      combinedAvgNumber: ["No"],
      maxSizeSounds: ["No"],
      maxSizeRepaired: ["No"],
      avgNoRepaired: ["No"],
      mineralStreaks: ["Slight"],
      barkPockets: ["No"],
      wormTracks: ["No"],
      vineMarks: ["Occasional"],
      crossBars: ["Occasional"],
      roughCutRupturedGrain: ["No	"],
      blendedRepairedTaperingHairlineSplits: ["Two 1/16 in. x 6 in."],
      repairs: ["Small Blending"],
      gumSpots: ["Occasional Gum spots in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    B: {
      sapwood: ["No^a	"],
      heartwood: ["Yes"],
      colorStreaksOrSpots: ["Yes"],
      colorVariation: ["Yes"],
      sharpColorContrastsAtJoints: ["Yes if Slip, Plank or Random matched	"],
      bookMatched: ["Specify"],
      slipMatched: ["Specify"],
      pleasingMatched: ["Yes"],
      plainS: ["3 in."],
      quarRift: ["3 in."],
      rotary: ["4 in."],
      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: [
        "2 per 1 sq ft 64 per 4 ft x 8 ft panel",
      ],
      conspicuousBurlsMaxSize: ["1/2 in."],
      avgNumber: ["1 per 1 sq ft 32 per 4 x 8 ft"],
      maxSize: ["1/8 in."],
      darkPartTotal: ["1/4 in."],
      combinedAvgNumber: ["1 per 8 sq ft 4 per 4 x 8 ft panel"],
      maxSizeSounds: ["3/8 in."],
      maxSizeRepaired: ["1/8 in."],
      avgNoRepaired: ["1 per 8 sq ft"],

      mineralStreaks: ["Yes"],
      barkPockets: ["Few to 1/8 in. x 1 in.	"],
      wormTracks: ["Slight"],
      vineMarks: ["Yes"],
      crossBars: ["Yes"],
      roughCutRupturedGrain: ["Slight"],
      blendedRepairedTaperingHairlineSplits: ["Four 1/8 in. x 8 in.	"],
      repairs: ["Blending"],
      gumSpots: ["Occasional Gum spots in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    C: {
      sapwood: ["Yes"],
      heartwood: ["Yes"],
      colorStreaksOrSpots: ["Yes"],
      colorVariation: ["Yes"],
      sharpColorContrastsAtJoints: ["Yes"],

      bookMatched: ["--"],
      slipMatched: ["--"],
      pleasingMatched: ["--"],
      plainS: ["No Limit"],
      quarRift: ["No Limit"],
      rotary: ["No Limit"],
      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: ["No Limit"],
      conspicuousBurlsMaxSize: ["No Limit"],
      avgNumber: ["No Limit"],
      maxSize: ["No Limit"],
      darkPartTotal: ["No Limit"],

      combinedAvgNumber: ["1 per 4 sq ft 8 per 4 x 8 ft panel"],
      maxSizeSounds: ["1/2 in."],
      maxSizeRepaired: ["1/2 in."],
      avgNoRepaired: ["1 per 8 sq ft"],

      mineralStreaks: ["Yes"],
      barkPockets: ["Few to 1/4 in. x 1 in.	"],
      wormTracks: ["Few"],
      vineMarks: ["Yes"],
      crossBars: ["Yes"],

      roughCutRupturedGrain: ["Slight"],
      blendedRepairedTaperingHairlineSplits: ["Four 3/16 in. x 8 in."],
      repairs: ["Yes"],
      gumSpots: ["Gum spots and gum streaks in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    D: {
      sapwood: ["Yes"],
      heartwood: ["Yes"],
      colorStreaksOrSpots: ["Yes"],
      colorVariation: ["Yes"],
      sharpColorContrastsAtJoints: ["Yes"],

      bookMatched: ["--"],
      slipMatched: ["--"],
      pleasingMatched: ["--"],
      plainS: ["No Limit"],
      quarRift: ["No Limit"],
      rotary: ["No Limit"],
      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: ["No Limit"],
      conspicuousBurlsMaxSize: ["No Limit"],
      avgNumber: ["No Limit"],
      maxSize: ["No Limit"],
      darkPartTotal: ["No Limit"],

      combinedAvgNumber: ["1 per 3 sq ft 10 per 4 x 8 ft panel"],
      maxSizeSounds: ["1 in."],
      maxSizeRepaired: ["3/4 in."],
      avgNoRepaired: ["1 per 6 sq ft"],

      mineralStreaks: ["Yes"],
      barkPockets: ["1/4 in. x 2 in."],
      wormTracks: ["Yes"],
      vineMarks: ["Yes"],
      crossBars: ["Yes"],

      roughCutRupturedGrain: ["Two 8 in. dia. areas or equivalent"],
      blendedRepairedTaperingHairlineSplits: ["Six 1/4 in. x 10 in."],
      repairs: ["Yes"],
      gumSpots: ["Gum spots and gum streaks in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
  },
  maple: {
    AA: {
      sapwood: ["Yes", "No", "Yes"],
      heartwood: ["No", "Yes", "Yes"],
      colorStreaksOrSpots: ["Slight"],
      colorVariation: ["Slight", "Yes"],
      sharpColorContrastsAtJoints: ["Yes if Slip, Plank or Random matched	"],
      bookMatched: ["Yes"],
      slipMatched: ["Specify"],
      pleasingMatched: ["--"],
      plainS: ["6 in."],
      quarRift: ["3 in."],
      rotary: ["6 in."],
      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: [
        "1 per 5 sq ft 6 per 4 ft x 8 ft panel",
      ],
      conspicuousBurlsMaxSize: ["1/4 in."],
      avgNumber: ["No"],
      maxSize: ["No"],
      darkPartTotal: ["No"],
      combinedAvgNumber: ["No"],
      maxSizeSounds: ["No"],
      maxSizeRepaired: ["No"],
      avgNoRepaired: ["No"],
      mineralStreaks: ["No; Maple, slight"],
      barkPockets: ["No"],
      wormTracks: ["Slight"],
      vineMarks: ["Slight"],
      crossBars: ["Slight"],
      roughCutRupturedGrain: ["No	"],
      blendedRepairedTaperingHairlineSplits: [
        " Two 1/32 in. x 3 in. on panel ends only",
      ],
      repairs: ["Very Small Blending"],
      gumSpots: ["Occasional Gum spots in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    A: {
      sapwood: ["Yes", "No", "Yes"],
      heartwood: ["No", "Yes", "Yes"],
      colorStreaksOrSpots: ["Slight", "Yes"],
      colorVariation: ["Slight", "Yes"],
      sharpColorContrastsAtJoints: ["Yes if Slip, Plank or Random matched	"],
      bookMatched: ["Yes"],
      slipMatched: ["Specify"],
      pleasingMatched: ["--"],
      plainS: ["5 in."],
      quarRift: ["3 in."],
      rotary: ["5 in."],

      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: [
        "1 per 3 sq ft 10 per 4 ft x 8 ft",
      ],
      conspicuousBurlsMaxSize: ["3/8 in."],
      avgNumber: ["1 per 8 sq ft 4 per 4 x 8 ft panel"],
      maxSize: ["1/8 in."],
      darkPartTotal: ["1/4 in."],
      combinedAvgNumber: ["No"],
      maxSizeSounds: ["No"],
      maxSizeRepaired: ["No"],
      avgNoRepaired: ["No"],
      mineralStreaks: ["Slight"],
      barkPockets: ["No"],
      wormTracks: ["Slight"],
      vineMarks: ["Slight"],
      crossBars: ["Slight"],
      roughCutRupturedGrain: ["No	"],
      blendedRepairedTaperingHairlineSplits: ["Two 1/16 in. x 6 in. "],
      repairs: ["Small Blending"],
      gumSpots: ["Occasional Gum spots in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    B: {
      sapwood: ["Yes", "No", "Yes"],
      heartwood: ["No", "Yes", "Yes"],
      colorStreaksOrSpots: ["Yes"],
      colorVariation: ["Yes"],
      sharpColorContrastsAtJoints: ["Yes if Slip, Plank or Random matched	"],
      bookMatched: ["Yes"],
      slipMatched: ["Specify"],
      pleasingMatched: ["--"],
      plainS: ["3 in."],
      quarRift: ["3 in."],
      rotary: ["4 in."],

      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: [
        "1 per 2 sq ft 16 per 4 ft x 8 ft panelLimit",
      ],
      conspicuousBurlsMaxSize: ["1/2 in."],
      avgNumber: ["1 per 8 sq ft 4 per 4 x 8 ft panel"],
      maxSize: ["1/8 in."],
      darkPartTotal: ["1/4 in."],
      combinedAvgNumber: ["1 per 8 sq ft 4 per 4 x 8 ft panel"],
      maxSizeSounds: ["3/8 in."],
      maxSizeRepaired: ["1/8 in."],
      avgNoRepaired: ["1 per 8 sq ft"],
      mineralStreaks: ["Slight"],
      barkPockets: ["Few to 1/8 in. x 1 in. "],
      wormTracks: ["Slight; Ash, yes"],
      vineMarks: ["Slight"],
      crossBars: ["Yes"],
      roughCutRupturedGrain: ["Slight"],
      blendedRepairedTaperingHairlineSplits: ["Four 1/8 in. x 8 in."],
      repairs: ["Blending"],
      gumSpots: ["Occasional Gum spots in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    C: {
      sapwood: ["Yes"],
      heartwood: ["Yes"],
      colorStreaksOrSpots: ["Yes"],
      colorVariation: ["Yes"],
      sharpColorContrastsAtJoints: ["Yes"],
      bookMatched: ["--"],
      slipMatched: ["--"],
      pleasingMatched: ["--"],
      plainS: ["No Limit"],
      quarRift: ["No Limit"],
      rotary: ["No Limit"],
      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: ["No Limit"],
      conspicuousBurlsMaxSize: ["No Limit"],
      avgNumber: ["No Limit"],
      maxSize: ["No Limit"],
      darkPartTotal: ["No Limit"],
      combinedAvgNumber: ["1 per 4 sq ft 4 per 4 x 8 ft panel"],
      maxSizeSounds: ["1/2 in."],
      maxSizeRepaired: ["1/2 in."],
      avgNoRepaired: ["1  per 8 sq ft"],
      mineralStreaks: ["Yes"],
      barkPockets: ["Few to 1/4 in. x 2 in."],
      wormTracks: ["Yes"],
      vineMarks: ["Yes"],
      crossBars: ["Yes"],
      roughCutRupturedGrain: ["Two 8 in. diameter areas or equivalent"],
      blendedRepairedTaperingHairlineSplits: ["Four 3/16 in. x 8 in."],
      repairs: ["Yes"],
      gumSpots: ["Gum spots and gum streaks in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    D: {
      sapwood: ["Yes"],
      heartwood: ["Yes"],
      colorStreaksOrSpots: ["Yes"],
      colorVariation: ["Yes"],
      sharpColorContrastsAtJoints: ["Yes"],
      bookMatched: ["--"],
      slipMatched: ["--"],
      pleasingMatched: ["--"],
      plainS: ["No Limit"],
      quarRift: ["No Limit"],
      rotary: ["No Limit"],
      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: ["No Limit"],
      conspicuousBurlsMaxSize: ["No Limit"],
      avgNumber: ["No Limit"],
      maxSize: ["No Limit"],
      darkPartTotal: ["No Limit"],
      combinedAvgNumber: ["1 per 3 sq ft 10 per 4 x 8 ft panel"],
      maxSizeSounds: ["1 in."],
      maxSizeRepaired: ["3/4 in."],
      avgNoRepaired: ["1 per 86sq ft"],
      mineralStreaks: ["Yes"],
      barkPockets: ["1/4 in. x 2 in."],
      wormTracks: ["Yes"],
      vineMarks: ["Yes"],
      crossBars: ["Yes"],
      roughCutRupturedGrain: ["5% of panel"],
      blendedRepairedTaperingHairlineSplits: ["Six  1/4 in. x 10 in."],
      repairs: ["Yes"],
      gumSpots: ["Gum spots and gum streaks in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
  },
  birch: {
    AA: {
      sapwood: ["Yes", "No", "Yes"],
      heartwood: ["No", "Yes", "Yes"],
      colorStreaksOrSpots: ["Slight"],
      colorVariation: ["Slight", "Yes"],
      sharpColorContrastsAtJoints: ["Yes if Slip, Plank or Random matched	"],
      bookMatched: ["Yes"],
      slipMatched: ["Specify"],
      pleasingMatched: ["--"],
      plainS: ["6 in."],
      quarRift: ["3 in."],
      rotary: ["6 in."],
      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: [
        "1 per 5 sq ft 6 per 4 ft x 8 ft panel",
      ],
      conspicuousBurlsMaxSize: ["1/4 in."],
      avgNumber: ["No"],
      maxSize: ["No"],
      darkPartTotal: ["No"],

      combinedAvgNumber: ["No"],
      maxSizeSounds: ["No"],
      maxSizeRepaired: ["No"],
      avgNoRepaired: ["No"],
      mineralStreaks: ["No; Maple, slight"],
      barkPockets: ["No"],
      wormTracks: ["Slight"],
      vineMarks: ["Slight"],
      crossBars: ["Slight"],
      roughCutRupturedGrain: ["No	"],
      blendedRepairedTaperingHairlineSplits: [
        " Two 1/32 in. x 3 in. on panel ends only",
      ],
      repairs: ["Very Small Blending"],
      gumSpots: ["Occasional Gum spots in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    A: {
      sapwood: ["Yes", "No", "Yes"],
      heartwood: ["No", "Yes", "Yes"],
      colorStreaksOrSpots: ["Slight", "Yes"],
      colorVariation: ["Slight", "Yes"],
      sharpColorContrastsAtJoints: ["Yes if Slip, Plank or Random matched	"],
      bookMatched: ["Yes"],
      slipMatched: ["Specify"],
      pleasingMatched: ["--"],
      plainS: ["5 in."],
      quarRift: ["3 in."],
      rotary: ["5 in."],

      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: [
        "1 per 3 sq ft 10 per 4 ft x 8 ft",
      ],
      conspicuousBurlsMaxSize: ["3/8 in."],
      avgNumber: ["1 per 8 sq ft 4 per 4 x 8 ft panel"],
      maxSize: ["1/8 in."],
      darkPartTotal: ["1/4 in."],
      combinedAvgNumber: ["No"],
      maxSizeSounds: ["No"],
      maxSizeRepaired: ["No"],
      avgNoRepaired: ["No"],
      mineralStreaks: ["Slight"],
      barkPockets: ["No"],
      wormTracks: ["Slight"],
      vineMarks: ["Slight"],
      crossBars: ["Slight"],
      roughCutRupturedGrain: ["No	"],
      blendedRepairedTaperingHairlineSplits: ["Two 1/16 in. x 6 in. "],
      repairs: ["Small Blending"],
      gumSpots: ["Occasional Gum spots in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    B: {
      sapwood: ["Yes", "No", "Yes"],
      heartwood: ["No", "Yes", "Yes"],
      colorStreaksOrSpots: ["Yes"],
      colorVariation: ["Yes"],
      sharpColorContrastsAtJoints: ["Yes if Slip, Plank or Random matched	"],
      bookMatched: ["Yes"],
      slipMatched: ["Specify"],
      pleasingMatched: ["--"],
      plainS: ["3 in."],
      quarRift: ["3 in."],
      rotary: ["4 in."],

      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: [
        "1 per 2 sq ft 16 per 4 ft x 8 ft panelLimit",
      ],
      conspicuousBurlsMaxSize: ["1/2 in."],
      avgNumber: ["1 per 4 sq ft 8 per 4 x 8 ft panel"],
      maxSize: ["1/8 in."],
      darkPartTotal: ["1/4 in."],
      combinedAvgNumber: ["1 per 4 sq ft 8 per 4 x 8 ft panel"],
      maxSizeSounds: ["3/8 in."],
      maxSizeRepaired: ["1/8 in."],
      avgNoRepaired: ["1 per 8 sq ft"],
      mineralStreaks: ["Slight"],
      barkPockets: ["Few to 1/8 in. x 1 in. "],
      wormTracks: ["Slight; Ash, yes"],
      vineMarks: ["Slight"],
      crossBars: ["Yes"],
      roughCutRupturedGrain: ["Slight"],
      blendedRepairedTaperingHairlineSplits: ["Four 1/8 in. x 8 in."],
      repairs: ["Blending"],
      gumSpots: ["Occasional Gum spots in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    C: {
      sapwood: ["Yes"],
      heartwood: ["Yes"],
      colorStreaksOrSpots: ["Yes"],
      colorVariation: ["Yes"],
      sharpColorContrastsAtJoints: ["Yes"],
      bookMatched: ["--"],
      slipMatched: ["--"],
      pleasingMatched: ["--"],
      plainS: ["No Limit"],
      quarRift: ["No Limit"],
      rotary: ["No Limit"],
      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: ["No Limit"],
      conspicuousBurlsMaxSize: ["No Limit"],
      avgNumber: ["No Limit"],
      maxSize: ["No Limit"],
      darkPartTotal: ["No Limit"],
      combinedAvgNumber: ["1 per 4 sq ft 4 per 4 x 8 ft panel"],
      maxSizeSounds: ["1/2 in."],
      maxSizeRepaired: ["1/2 in."],

      avgNoRepaired: ["1  per 8 sq ft"],
      mineralStreaks: ["Yes"],
      barkPockets: ["Few to 1/4 in. x 2 in."],
      wormTracks: ["Yes"],
      vineMarks: ["Yes"],
      crossBars: ["Yes"],
      roughCutRupturedGrain: ["Two 8 in. diameter areas or equivalent"],
      blendedRepairedTaperingHairlineSplits: ["Four 3/16 in. x 8 in."],
      repairs: ["Yes"],
      gumSpots: ["Gum spots and gum streaks in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    D: {
      sapwood: ["Yes"],
      heartwood: ["Yes"],
      colorStreaksOrSpots: ["Yes"],
      colorVariation: ["Yes"],
      sharpColorContrastsAtJoints: ["Yes"],
      bookMatched: ["--"],
      slipMatched: ["--"],
      pleasingMatched: ["--"],
      plainS: ["No Limit"],
      quarRift: ["No Limit"],
      rotary: ["No Limit"],
      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: ["No Limit"],
      conspicuousBurlsMaxSize: ["No Limit"],
      avgNumber: ["No Limit"],
      maxSize: ["No Limit"],
      darkPartTotal: ["No Limit"],
      combinedAvgNumber: ["1 per 3 sq ft 10 per 4 x 8 ft panel"],
      maxSizeSounds: ["1 in."],
      maxSizeRepaired: ["3/4 in."],
      avgNoRepaired: ["1 per 86sq ft"],
      mineralStreaks: ["Yes"],
      barkPockets: ["1/4 in. x 2 in."],
      wormTracks: ["Yes"],
      vineMarks: ["Yes"],
      crossBars: ["Yes"],
      roughCutRupturedGrain: ["1/4 in. x 2 in."],
      blendedRepairedTaperingHairlineSplits: ["Six  1/4 in. x 10 in."],
      repairs: ["Yes"],
      gumSpots: ["Gum spots and gum streaks in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
  },
  oak: {
    AA: {
      sapwood: ["Yes", "No", "Yes"],
      heartwood: ["No", "Yes", "Yes"],
      colorStreaksOrSpots: ["Slight"],
      colorVariation: ["Slight", "Yes"],
      sharpColorContrastsAtJoints: ["Yes if Slip, Plank or Random matched	"],
      bookMatched: ["Yes"],
      slipMatched: ["Specify"],
      pleasingMatched: ["--"],
      plainS: ["6 in."],
      quarRift: ["3 in."],
      rotary: ["6 in."],
      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: [
        "1 per 5 sq ft 6 per 4 ft x 8 ft panel",
      ],
      conspicuousBurlsMaxSize: ["1/4 in."],
      avgNumber: ["No"],
      maxSize: ["No"],
      darkPartTotal: ["No"],

      combinedAvgNumber: ["No"],
      maxSizeSounds: ["No"],
      maxSizeRepaired: ["No"],
      avgNoRepaired: ["No"],
      mineralStreaks: ["No; Maple, slight"],
      barkPockets: ["No"],
      wormTracks: ["Slight"],
      vineMarks: ["Slight"],
      crossBars: ["Slight"],
      roughCutRupturedGrain: ["No	"],
      blendedRepairedTaperingHairlineSplits: [
        " Two 1/32 in. x 3 in. on panel ends only",
      ],
      repairs: ["Very Small Blending"],
      gumSpots: ["Occasional Gum spots in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    A: {
      sapwood: ["Yes", "No", "Yes"],
      heartwood: ["No", "Yes", "Yes"],
      colorStreaksOrSpots: ["Slight", "Yes"],
      colorVariation: ["Slight", "Yes"],
      sharpColorContrastsAtJoints: ["Yes if Slip, Plank or Random matched	"],
      bookMatched: ["Yes"],
      slipMatched: ["Specify"],
      pleasingMatched: ["--"],
      plainS: ["5 in."],
      quarRift: ["3 in."],
      rotary: ["5 in."],

      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: [
        "1 per 3 sq ft 10 per 4 ft x 8 ft",
      ],
      conspicuousBurlsMaxSize: ["3/8 in."],
      avgNumber: ["1 per 8 sq ft 4 per 4 x 8 ft panel"],
      maxSize: ["1/8 in."],
      darkPartTotal: ["1/4 in."],
      combinedAvgNumber: ["No"],
      maxSizeSounds: ["No"],
      maxSizeRepaired: ["No"],
      avgNoRepaired: ["No"],
      mineralStreaks: ["Slight"],
      barkPockets: ["No"],
      wormTracks: ["Slight"],
      vineMarks: ["Slight"],
      crossBars: ["Slight"],
      roughCutRupturedGrain: ["No	"],
      blendedRepairedTaperingHairlineSplits: ["Two 1/16 in. x 6 in. "],
      repairs: ["Small Blending"],
      gumSpots: ["Occasional Gum spots in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    B: {
      sapwood: ["Yes", "No", "Yes"],
      heartwood: ["No", "Yes", "Yes"],
      colorStreaksOrSpots: ["Yes"],
      colorVariation: ["Yes"],
      sharpColorContrastsAtJoints: ["Yes if Slip, Plank or Random matched	"],
      bookMatched: ["Yes"],
      slipMatched: ["Specify"],
      pleasingMatched: ["--"],
      plainS: ["3 in."],
      quarRift: ["3 in."],
      rotary: ["4 in."],

      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: [
        "1 per 2 sq ft 16 per 4 ft x 8 ft panelLimit",
      ],
      conspicuousBurlsMaxSize: ["1/2 in."],
      avgNumber: ["1 per 4 sq ft 8 per 4 x 8 ft panel"],
      maxSize: ["1/8 in."],
      darkPartTotal: ["1/4 in."],
      combinedAvgNumber: ["1 per 4 sq ft 8 per 4 x 8 ft panel"],
      maxSizeSounds: ["3/8 in."],
      maxSizeRepaired: ["1/8 in."],
      avgNoRepaired: ["1 per 8 sq ft"],
      mineralStreaks: ["Slight"],
      barkPockets: ["Few to 1/8 in. x 1 in. "],
      wormTracks: ["Slight; Ash, yes"],
      vineMarks: ["Slight"],
      crossBars: ["Yes"],
      roughCutRupturedGrain: ["Slight"],
      blendedRepairedTaperingHairlineSplits: ["Four 1/8 in. x 8 in."],
      repairs: ["Blending"],
      gumSpots: ["Occasional Gum spots in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    C: {
      sapwood: ["Yes"],
      heartwood: ["Yes"],
      colorStreaksOrSpots: ["Yes"],
      colorVariation: ["Yes"],
      sharpColorContrastsAtJoints: ["Yes"],
      bookMatched: ["--"],
      slipMatched: ["--"],
      pleasingMatched: ["--"],
      plainS: ["No Limit"],
      quarRift: ["No Limit"],
      rotary: ["No Limit"],
      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: ["No Limit"],
      conspicuousBurlsMaxSize: ["No Limit"],
      avgNumber: ["No Limit"],
      maxSize: ["No Limit"],
      darkPartTotal: ["No Limit"],
      combinedAvgNumber: ["1 per 4 sq ft 4 per 4 x 8 ft panel"],
      maxSizeSounds: ["1/2 in."],
      maxSizeRepaired: ["1/2 in."],

      avgNoRepaired: ["1  per 8 sq ft"],
      mineralStreaks: ["Yes"],
      barkPockets: ["Few to 1/4 in. x 2 in."],
      wormTracks: ["Yes"],
      vineMarks: ["Yes"],
      crossBars: ["Yes"],
      roughCutRupturedGrain: ["Two 8 in. diameter areas or equivalent"],
      blendedRepairedTaperingHairlineSplits: ["Four 3/16 in. x 8 in."],
      repairs: ["Yes"],
      gumSpots: ["Gum spots and gum streaks in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    D: {
      sapwood: ["Yes"],
      heartwood: ["Yes"],
      colorStreaksOrSpots: ["Yes"],
      colorVariation: ["Yes"],
      sharpColorContrastsAtJoints: ["Yes"],
      bookMatched: ["--"],
      slipMatched: ["--"],
      pleasingMatched: ["--"],
      plainS: ["No Limit"],
      quarRift: ["No Limit"],
      rotary: ["No Limit"],
      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: ["No Limit"],
      conspicuousBurlsMaxSize: ["No Limit"],
      avgNumber: ["No Limit"],
      maxSize: ["No Limit"],
      darkPartTotal: ["No Limit"],
      combinedAvgNumber: ["1 per 3 sq ft 10 per 4 x 8 ft panel"],
      maxSizeSounds: ["1 in."],
      maxSizeRepaired: ["3/4 in."],
      avgNoRepaired: ["1 per 86sq ft"],
      mineralStreaks: ["Yes"],
      barkPockets: ["1/4 in. x 2 in."],
      wormTracks: ["Yes"],
      vineMarks: ["Yes"],
      crossBars: ["Yes"],
      roughCutRupturedGrain: ["1/4 in. x 2 in."],
      blendedRepairedTaperingHairlineSplits: ["Six  1/4 in. x 10 in."],
      repairs: ["Yes"],
      gumSpots: ["Gum spots and gum streaks in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
  },
  ceder: {
    AA: {
      sapwood: ["Yes", "No", "Yes"],
      heartwood: ["No", "Yes", "Yes"],
      colorStreaksOrSpots: ["Slight"],
      colorVariation: ["Slight", "Yes"],
      sharpColorContrastsAtJoints: ["Yes if Slip, Plank or Random matched	"],
      bookMatched: ["Yes"],
      slipMatched: ["Specify"],
      pleasingMatched: ["--"],
      plainS: ["6 in."],
      quarRift: ["3 in."],
      rotary: ["6 in."],
      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: [
        "1 per 5 sq ft 6 per 4 ft x 8 ft panel",
      ],
      conspicuousBurlsMaxSize: ["1/4 in."],
      avgNumber: ["No"],
      maxSize: ["No"],
      darkPartTotal: ["No"],

      combinedAvgNumber: ["No"],
      maxSizeSounds: ["No"],
      maxSizeRepaired: ["No"],
      avgNoRepaired: ["No"],
      mineralStreaks: ["No; Maple, slight"],
      barkPockets: ["No"],
      wormTracks: ["Slight"],
      vineMarks: ["Slight"],
      crossBars: ["Slight"],
      roughCutRupturedGrain: ["No	"],
      blendedRepairedTaperingHairlineSplits: [
        " Two 1/32 in. x 3 in. on panel ends only",
      ],
      repairs: ["Very Small Blending"],
      gumSpots: ["Occasional Gum spots in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    A: {
      sapwood: ["Yes", "No", "Yes"],
      heartwood: ["No", "Yes", "Yes"],
      colorStreaksOrSpots: ["Slight", "Yes"],
      colorVariation: ["Slight", "Yes"],
      sharpColorContrastsAtJoints: ["Yes if Slip, Plank or Random matched	"],
      bookMatched: ["Yes"],
      slipMatched: ["Specify"],
      pleasingMatched: ["--"],
      plainS: ["5 in."],
      quarRift: ["3 in."],
      rotary: ["5 in."],

      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: [
        "1 per 3 sq ft 10 per 4 ft x 8 ft",
      ],
      conspicuousBurlsMaxSize: ["3/8 in."],
      avgNumber: ["1 per 8 sq ft 4 per 4 x 8 ft panel"],
      maxSize: ["1/8 in."],
      darkPartTotal: ["1/4 in."],
      combinedAvgNumber: ["No"],
      maxSizeSounds: ["No"],
      maxSizeRepaired: ["No"],
      avgNoRepaired: ["No"],
      mineralStreaks: ["Slight"],
      barkPockets: ["No"],
      wormTracks: ["Slight"],
      vineMarks: ["Slight"],
      crossBars: ["Slight"],
      roughCutRupturedGrain: ["No	"],
      blendedRepairedTaperingHairlineSplits: ["Two 1/16 in. x 6 in. "],
      repairs: ["Small Blending"],
      gumSpots: ["Occasional Gum spots in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    B: {
      sapwood: ["Yes", "No", "Yes"],
      heartwood: ["No", "Yes", "Yes"],
      colorStreaksOrSpots: ["Yes"],
      colorVariation: ["Yes"],
      sharpColorContrastsAtJoints: ["Yes if Slip, Plank or Random matched	"],
      bookMatched: ["Yes"],
      slipMatched: ["Specify"],
      pleasingMatched: ["--"],
      plainS: ["3 in."],
      quarRift: ["3 in."],
      rotary: ["4 in."],

      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: [
        "1 per 2 sq ft 16 per 4 ft x 8 ft panelLimit",
      ],
      conspicuousBurlsMaxSize: ["1/2 in."],
      avgNumber: ["1 per 4 sq ft 8 per 4 x 8 ft panel"],
      maxSize: ["1/8 in."],
      darkPartTotal: ["1/4 in."],
      combinedAvgNumber: ["1 per 4 sq ft 8 per 4 x 8 ft panel"],
      maxSizeSounds: ["3/8 in."],
      maxSizeRepaired: ["1/8 in."],
      avgNoRepaired: ["1 per 8 sq ft"],
      mineralStreaks: ["Slight"],
      barkPockets: ["Few to 1/8 in. x 1 in. "],
      wormTracks: ["Slight; Ash, yes"],
      vineMarks: ["Slight"],
      crossBars: ["Yes"],
      roughCutRupturedGrain: ["Slight"],
      blendedRepairedTaperingHairlineSplits: ["Four 1/8 in. x 8 in."],
      repairs: ["Blending"],
      gumSpots: ["Occasional Gum spots in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    C: {
      sapwood: ["Yes"],
      heartwood: ["Yes"],
      colorStreaksOrSpots: ["Yes"],
      colorVariation: ["Yes"],
      sharpColorContrastsAtJoints: ["Yes"],
      bookMatched: ["--"],
      slipMatched: ["--"],
      pleasingMatched: ["--"],
      plainS: ["No Limit"],
      quarRift: ["No Limit"],
      rotary: ["No Limit"],
      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: ["No Limit"],
      conspicuousBurlsMaxSize: ["No Limit"],
      avgNumber: ["No Limit"],
      maxSize: ["No Limit"],
      darkPartTotal: ["No Limit"],
      combinedAvgNumber: ["1 per 4 sq ft 4 per 4 x 8 ft panel"],
      maxSizeSounds: ["1/2 in."],
      maxSizeRepaired: ["1/2 in."],

      avgNoRepaired: ["1  per 8 sq ft"],
      mineralStreaks: ["Yes"],
      barkPockets: ["Few to 1/4 in. x 2 in."],
      wormTracks: ["Yes"],
      vineMarks: ["Yes"],
      crossBars: ["Yes"],
      roughCutRupturedGrain: ["Two 8 in. diameter areas or equivalent"],
      blendedRepairedTaperingHairlineSplits: ["Four 3/16 in. x 8 in."],
      repairs: ["Yes"],
      gumSpots: ["Gum spots and gum streaks in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    D: {
      sapwood: ["Yes"],
      heartwood: ["Yes"],
      colorStreaksOrSpots: ["Yes"],
      colorVariation: ["Yes"],
      sharpColorContrastsAtJoints: ["Yes"],
      bookMatched: ["--"],
      slipMatched: ["--"],
      pleasingMatched: ["--"],
      plainS: ["No Limit"],
      quarRift: ["No Limit"],
      rotary: ["No Limit"],
      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: ["No Limit"],
      conspicuousBurlsMaxSize: ["No Limit"],
      avgNumber: ["No Limit"],
      maxSize: ["No Limit"],
      darkPartTotal: ["No Limit"],
      combinedAvgNumber: ["1 per 3 sq ft 10 per 4 x 8 ft panel"],
      maxSizeSounds: ["1 in."],
      maxSizeRepaired: ["3/4 in."],
      avgNoRepaired: ["1 per 86sq ft"],
      mineralStreaks: ["Yes"],
      barkPockets: ["1/4 in. x 2 in."],
      wormTracks: ["Yes"],
      vineMarks: ["Yes"],
      crossBars: ["Yes"],
      roughCutRupturedGrain: ["1/4 in. x 2 in."],
      blendedRepairedTaperingHairlineSplits: ["Six  1/4 in. x 10 in."],
      repairs: ["Yes"],
      gumSpots: ["Gum spots and gum streaks in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
  },
  pine: {
    AA: {
      sapwood: ["Yes", "No", "Yes"],
      heartwood: ["No", "Yes", "Yes"],
      colorStreaksOrSpots: ["Slight"],
      colorVariation: ["Slight", "Yes"],
      sharpColorContrastsAtJoints: ["Yes if Slip, Plank or Random matched	"],
      bookMatched: ["Yes"],
      slipMatched: ["Specify"],
      pleasingMatched: ["--"],
      plainS: ["6 in."],
      quarRift: ["3 in."],
      rotary: ["6 in."],
      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: [
        "1 per 5 sq ft 6 per 4 ft x 8 ft panel",
      ],
      conspicuousBurlsMaxSize: ["1/4 in."],
      avgNumber: ["No"],
      maxSize: ["No"],
      darkPartTotal: ["No"],

      combinedAvgNumber: ["No"],
      maxSizeSounds: ["No"],
      maxSizeRepaired: ["No"],
      avgNoRepaired: ["No"],
      mineralStreaks: ["No; Maple, slight"],
      barkPockets: ["No"],
      wormTracks: ["Slight"],
      vineMarks: ["Slight"],
      crossBars: ["Slight"],
      roughCutRupturedGrain: ["No	"],
      blendedRepairedTaperingHairlineSplits: [
        " Two 1/32 in. x 3 in. on panel ends only",
      ],
      repairs: ["Very Small Blending"],
      gumSpots: ["Occasional Gum spots in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    A: {
      sapwood: ["Yes", "No", "Yes"],
      heartwood: ["No", "Yes", "Yes"],
      colorStreaksOrSpots: ["Slight", "Yes"],
      colorVariation: ["Slight", "Yes"],
      sharpColorContrastsAtJoints: ["Yes if Slip, Plank or Random matched	"],
      bookMatched: ["Yes"],
      slipMatched: ["Specify"],
      pleasingMatched: ["--"],
      plainS: ["5 in."],
      quarRift: ["3 in."],
      rotary: ["5 in."],

      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: [
        "1 per 3 sq ft 10 per 4 ft x 8 ft",
      ],
      conspicuousBurlsMaxSize: ["3/8 in."],
      avgNumber: ["1 per 8 sq ft 4 per 4 x 8 ft panel"],
      maxSize: ["1/8 in."],
      darkPartTotal: ["1/4 in."],
      combinedAvgNumber: ["No"],
      maxSizeSounds: ["No"],
      maxSizeRepaired: ["No"],
      avgNoRepaired: ["No"],
      mineralStreaks: ["Slight"],
      barkPockets: ["No"],
      wormTracks: ["Slight"],
      vineMarks: ["Slight"],
      crossBars: ["Slight"],
      roughCutRupturedGrain: ["No	"],
      blendedRepairedTaperingHairlineSplits: ["Two 1/16 in. x 6 in. "],
      repairs: ["Small Blending"],
      gumSpots: ["Occasional Gum spots in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    B: {
      sapwood: ["Yes", "No", "Yes"],
      heartwood: ["No", "Yes", "Yes"],
      colorStreaksOrSpots: ["Yes"],
      colorVariation: ["Yes"],
      sharpColorContrastsAtJoints: ["Yes if Slip, Plank or Random matched	"],
      bookMatched: ["Yes"],
      slipMatched: ["Specify"],
      pleasingMatched: ["--"],
      plainS: ["3 in."],
      quarRift: ["3 in."],
      rotary: ["4 in."],

      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: [
        "1 per 2 sq ft 16 per 4 ft x 8 ft panelLimit",
      ],
      conspicuousBurlsMaxSize: ["1/2 in."],
      avgNumber: ["1 per 4 sq ft 8 per 4 x 8 ft panel"],
      maxSize: ["1/8 in."],
      darkPartTotal: ["1/4 in."],
      combinedAvgNumber: ["1 per 4 sq ft 8 per 4 x 8 ft panel"],
      maxSizeSounds: ["3/8 in."],
      maxSizeRepaired: ["1/8 in."],
      avgNoRepaired: ["1 per 8 sq ft"],
      mineralStreaks: ["Slight"],
      barkPockets: ["Few to 1/8 in. x 1 in. "],
      wormTracks: ["Slight; Ash, yes"],
      vineMarks: ["Slight"],
      crossBars: ["Yes"],
      roughCutRupturedGrain: ["Slight"],
      blendedRepairedTaperingHairlineSplits: ["Four 1/8 in. x 8 in."],
      repairs: ["Blending"],
      gumSpots: ["Occasional Gum spots in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    C: {
      sapwood: ["Yes"],
      heartwood: ["Yes"],
      colorStreaksOrSpots: ["Yes"],
      colorVariation: ["Yes"],
      sharpColorContrastsAtJoints: ["Yes"],
      bookMatched: ["--"],
      slipMatched: ["--"],
      pleasingMatched: ["--"],
      plainS: ["No Limit"],
      quarRift: ["No Limit"],
      rotary: ["No Limit"],
      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: ["No Limit"],
      conspicuousBurlsMaxSize: ["No Limit"],
      avgNumber: ["No Limit"],
      maxSize: ["No Limit"],
      darkPartTotal: ["No Limit"],
      combinedAvgNumber: ["1 per 4 sq ft 4 per 4 x 8 ft panel"],
      maxSizeSounds: ["1/2 in."],
      maxSizeRepaired: ["1/2 in."],

      avgNoRepaired: ["1  per 8 sq ft"],
      mineralStreaks: ["Yes"],
      barkPockets: ["Few to 1/4 in. x 2 in."],
      wormTracks: ["Yes"],
      vineMarks: ["Yes"],
      crossBars: ["Yes"],
      roughCutRupturedGrain: ["Two 8 in. diameter areas or equivalent"],
      blendedRepairedTaperingHairlineSplits: ["Four 3/16 in. x 8 in."],
      repairs: ["Yes"],
      gumSpots: ["Gum spots and gum streaks in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    D: {
      sapwood: ["Yes"],
      heartwood: ["Yes"],
      colorStreaksOrSpots: ["Yes"],
      colorVariation: ["Yes"],
      sharpColorContrastsAtJoints: ["Yes"],
      bookMatched: ["--"],
      slipMatched: ["--"],
      pleasingMatched: ["--"],
      plainS: ["No Limit"],
      quarRift: ["No Limit"],
      rotary: ["No Limit"],
      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: ["No Limit"],
      conspicuousBurlsMaxSize: ["No Limit"],
      avgNumber: ["No Limit"],
      maxSize: ["No Limit"],
      darkPartTotal: ["No Limit"],
      combinedAvgNumber: ["1 per 3 sq ft 10 per 4 x 8 ft panel"],
      maxSizeSounds: ["1 in."],
      maxSizeRepaired: ["3/4 in."],
      avgNoRepaired: ["1 per 86sq ft"],
      mineralStreaks: ["Yes"],
      barkPockets: ["1/4 in. x 2 in."],
      wormTracks: ["Yes"],
      vineMarks: ["Yes"],
      crossBars: ["Yes"],
      roughCutRupturedGrain: ["1/4 in. x 2 in."],
      blendedRepairedTaperingHairlineSplits: ["Six  1/4 in. x 10 in."],
      repairs: ["Yes"],
      gumSpots: ["Gum spots and gum streaks in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
  },
  redwood: {
    AA: {
      sapwood: ["No"],
      heartwood: ["Yes"],
      colorStreaksOrSpots: ["Yes"],
      colorVariation: ["Slight"],
      sharpColorContrastsAtJoints: ["Yes if Slip, Plank or Random matched	"],
      bookMatched: ["Yes"],
      slipMatched: ["Specify"],
      pleasingMatched: ["--"],
      plainS: ["6 in."],
      quarRift: ["3 in."],
      rotary: ["6 in."],
      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: [
        "1 per 4 sq ft 8 per 4 ft x 8 ft panel",
      ],
      conspicuousBurlsMaxSize: ["1/4 in."],
      avgNumber: ["No"],
      maxSize: ["No"],
      darkPartTotal: ["No"],

      combinedAvgNumber: ["No"],
      maxSizeSounds: ["No"],
      maxSizeRepaired: ["No"],
      avgNoRepaired: ["No"],
      mineralStreaks: ["No"],
      barkPockets: ["No"],
      wormTracks: ["No"],
      vineMarks: ["No"],
      crossBars: ["Slight"],
      roughCutRupturedGrain: ["No	"],
      blendedRepairedTaperingHairlineSplits: [
        " Two 1/32 in. x 3 in. on panel ends only",
      ],
      repairs: ["Very Small Blending"],
      gumSpots: ["Occasional Gum spots in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    A: {
      sapwood: ["5%a"],
      heartwood: ["Yes"],
      colorStreaksOrSpots: ["Yes"],
      colorVariation: ["Slight"],
      sharpColorContrastsAtJoints: ["Yes if Slip, Plank or Random matched	"],
      bookMatched: ["Yes"],
      slipMatched: ["Specify"],
      pleasingMatched: ["--"],
      plainS: ["5 in."],
      quarRift: ["3 in."],
      rotary: ["5 in."],

      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: [
        "1 per 2 2/3 sq ft 12 per 4 ft x 8 ft panel",
      ],
      conspicuousBurlsMaxSize: ["3/8 in."],
      avgNumber: ["1 per 3 sq ft 10 per 4 x 8 ft panel"],
      maxSize: ["1/8 in."],
      darkPartTotal: ["1/4 in."],
      combinedAvgNumber: ["No"],
      maxSizeSounds: ["No"],
      maxSizeRepaired: ["No"],
      avgNoRepaired: ["No"],
      mineralStreaks: ["Slight,Blending"],
      barkPockets: ["No"],
      wormTracks: ["No"],
      vineMarks: ["Slight"],
      crossBars: ["Slight"],
      roughCutRupturedGrain: ["No	"],
      blendedRepairedTaperingHairlineSplits: ["Two 1/16 in. x 6 in. "],
      repairs: ["Small Blending"],
      gumSpots: [""],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    B: {
      sapwood: ["Yes", "No", "Yes"],
      heartwood: ["No", "Yes", "Yes"],
      colorStreaksOrSpots: ["Yes"],
      colorVariation: ["Yes"],
      sharpColorContrastsAtJoints: ["Yes if Slip, Plank or Random matched	"],
      bookMatched: ["Yes"],
      slipMatched: ["Specify"],
      pleasingMatched: ["--"],
      plainS: ["3 in."],
      quarRift: ["3 in."],
      rotary: ["4 in."],

      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: [
        "1 per 2 sq ft 16 per 4 ft x 8 ft panelLimit",
      ],
      conspicuousBurlsMaxSize: ["1/2 in."],
      avgNumber: ["1 per 4 sq ft 8 per 4 x 8 ft panel"],
      maxSize: ["1/8 in."],
      darkPartTotal: ["1/4 in."],
      combinedAvgNumber: ["1 per 4 sq ft 8 per 4 x 8 ft panel"],
      maxSizeSounds: ["3/8 in."],
      maxSizeRepaired: ["1/8 in."],
      avgNoRepaired: ["1 per 8 sq ft"],
      mineralStreaks: ["Few to 12 in."],
      barkPockets: ["Few to 1/8 in. x 1 in. "],
      wormTracks: ["Slight"],
      vineMarks: ["Yes"],
      crossBars: ["Yes"],
      roughCutRupturedGrain: ["Slight"],
      blendedRepairedTaperingHairlineSplits: ["Four 1/8 in. x 8 in."],
      repairs: ["Blending"],
      gumSpots: [""],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    C: {
      sapwood: ["Yes"],
      heartwood: ["Yes"],
      colorStreaksOrSpots: ["Yes"],
      colorVariation: ["Yes"],
      sharpColorContrastsAtJoints: ["Yes"],
      bookMatched: ["--"],
      slipMatched: ["--"],
      pleasingMatched: ["--"],
      plainS: ["No Limit"],
      quarRift: ["No Limit"],
      rotary: ["No Limit"],
      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: ["No Limit"],
      conspicuousBurlsMaxSize: ["No Limit"],
      avgNumber: ["No Limit"],
      maxSize: ["No Limit"],
      darkPartTotal: ["No Limit"],
      combinedAvgNumber: ["1 per 4 sq ft 4 per 4 x 8 ft panel"],
      maxSizeSounds: ["1/2 in."],
      maxSizeRepaired: ["1/2 in."],

      avgNoRepaired: ["1  per 8 sq ft"],
      mineralStreaks: ["Yes"],
      barkPockets: ["Few to 1/4 in. x 2 in."],
      wormTracks: ["Yes"],
      vineMarks: ["Yes"],
      crossBars: ["Yes"],
      roughCutRupturedGrain: ["Two 8 in. diameter areas or equivalent"],
      blendedRepairedTaperingHairlineSplits: ["Four 3/16 in. x 8 in."],
      repairs: ["Yes"],
      gumSpots: ["Gum spots and gum streaks in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    D: {
      sapwood: ["Yes"],
      heartwood: ["Yes"],
      colorStreaksOrSpots: ["Yes"],
      colorVariation: ["Yes"],
      sharpColorContrastsAtJoints: ["Yes"],
      bookMatched: ["--"],
      slipMatched: ["--"],
      pleasingMatched: ["--"],
      plainS: ["No Limit"],
      quarRift: ["No Limit"],
      rotary: ["No Limit"],
      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: ["No Limit"],
      conspicuousBurlsMaxSize: ["No Limit"],
      avgNumber: ["No Limit"],
      maxSize: ["No Limit"],
      darkPartTotal: ["No Limit"],
      combinedAvgNumber: ["1 per 3 sq ft 10 per 4 x 8 ft panel"],
      maxSizeSounds: ["1 in."],
      maxSizeRepaired: ["3/4 in."],
      avgNoRepaired: ["1 per 86sq ft"],
      mineralStreaks: ["Yes"],
      barkPockets: ["1/4 in. x 2 in."],
      wormTracks: ["Yes"],
      vineMarks: ["Yes"],
      crossBars: ["Yes"],
      roughCutRupturedGrain: ["1/4 in. x 2 in."],
      blendedRepairedTaperingHairlineSplits: ["Six  1/4 in. x 10 in."],
      repairs: ["Yes"],
      gumSpots: ["Gum spots and gum streaks in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
  },
  fir: {
    AA: {
      sapwood: ["Yes", "No", "Yes"],
      heartwood: ["No", "Yes", "Yes"],
      colorStreaksOrSpots: ["Slight"],
      colorVariation: ["Slight", "Yes"],
      sharpColorContrastsAtJoints: ["Yes if Slip, Plank or Random matched	"],
      bookMatched: ["Yes"],
      slipMatched: ["Specify"],
      pleasingMatched: ["--"],
      plainS: ["6 in."],
      quarRift: ["3 in."],
      rotary: ["6 in."],
      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: [
        "1 per 5 sq ft 6 per 4 ft x 8 ft panel",
      ],
      conspicuousBurlsMaxSize: ["1/4 in."],
      avgNumber: ["No"],
      maxSize: ["No"],
      darkPartTotal: ["No"],

      combinedAvgNumber: ["No"],
      maxSizeSounds: ["No"],
      maxSizeRepaired: ["No"],
      avgNoRepaired: ["No"],
      mineralStreaks: ["No; Maple, slight"],
      barkPockets: ["No"],
      wormTracks: ["Slight"],
      vineMarks: ["Slight"],
      crossBars: ["Slight"],
      roughCutRupturedGrain: ["No	"],
      blendedRepairedTaperingHairlineSplits: [
        " Two 1/32 in. x 3 in. on panel ends only",
      ],
      repairs: ["Very Small Blending"],
      gumSpots: ["Occasional Gum spots in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    A: {
      sapwood: ["Yes", "No", "Yes"],
      heartwood: ["No", "Yes", "Yes"],
      colorStreaksOrSpots: ["Slight", "Yes"],
      colorVariation: ["Slight", "Yes"],
      sharpColorContrastsAtJoints: ["Yes if Slip, Plank or Random matched	"],
      bookMatched: ["Yes"],
      slipMatched: ["Specify"],
      pleasingMatched: ["--"],
      plainS: ["5 in."],
      quarRift: ["3 in."],
      rotary: ["5 in."],

      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: [
        "1 per 3 sq ft 10 per 4 ft x 8 ft",
      ],
      conspicuousBurlsMaxSize: ["3/8 in."],
      avgNumber: ["1 per 8 sq ft 4 per 4 x 8 ft panel"],
      maxSize: ["1/8 in."],
      darkPartTotal: ["1/4 in."],
      combinedAvgNumber: ["No"],
      maxSizeSounds: ["No"],
      maxSizeRepaired: ["No"],
      avgNoRepaired: ["No"],
      mineralStreaks: ["Slight"],
      barkPockets: ["No"],
      wormTracks: ["Slight"],
      vineMarks: ["Slight"],
      crossBars: ["Slight"],
      roughCutRupturedGrain: ["No	"],
      blendedRepairedTaperingHairlineSplits: ["Two 1/16 in. x 6 in. "],
      repairs: ["Small Blending"],
      gumSpots: ["Occasional Gum spots in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    B: {
      sapwood: ["Yes", "No", "Yes"],
      heartwood: ["No", "Yes", "Yes"],
      colorStreaksOrSpots: ["Yes"],
      colorVariation: ["Yes"],
      sharpColorContrastsAtJoints: ["Yes if Slip, Plank or Random matched	"],
      bookMatched: ["Yes"],
      slipMatched: ["Specify"],
      pleasingMatched: ["--"],
      plainS: ["3 in."],
      quarRift: ["3 in."],
      rotary: ["4 in."],

      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: [
        "1 per 2 sq ft 16 per 4 ft x 8 ft panelLimit",
      ],
      conspicuousBurlsMaxSize: ["1/2 in."],
      avgNumber: ["1 per 4 sq ft 8 per 4 x 8 ft panel"],
      maxSize: ["1/8 in."],
      darkPartTotal: ["1/4 in."],
      combinedAvgNumber: ["1 per 4 sq ft 8 per 4 x 8 ft panel"],
      maxSizeSounds: ["3/8 in."],
      maxSizeRepaired: ["1/8 in."],
      avgNoRepaired: ["1 per 8 sq ft"],
      mineralStreaks: ["Slight"],
      barkPockets: ["Few to 1/8 in. x 1 in. "],
      wormTracks: ["Slight; Ash, yes"],
      vineMarks: ["Slight"],
      crossBars: ["Yes"],
      roughCutRupturedGrain: ["Slight"],
      blendedRepairedTaperingHairlineSplits: ["Four 1/8 in. x 8 in."],
      repairs: ["Blending"],
      gumSpots: ["Occasional Gum spots in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    C: {
      sapwood: ["Yes"],
      heartwood: ["Yes"],
      colorStreaksOrSpots: ["Yes"],
      colorVariation: ["Yes"],
      sharpColorContrastsAtJoints: ["Yes"],
      bookMatched: ["--"],
      slipMatched: ["--"],
      pleasingMatched: ["--"],
      plainS: ["No Limit"],
      quarRift: ["No Limit"],
      rotary: ["No Limit"],
      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: ["No Limit"],
      conspicuousBurlsMaxSize: ["No Limit"],
      avgNumber: ["No Limit"],
      maxSize: ["No Limit"],
      darkPartTotal: ["No Limit"],
      combinedAvgNumber: ["1 per 4 sq ft 4 per 4 x 8 ft panel"],
      maxSizeSounds: ["1/2 in."],
      maxSizeRepaired: ["1/2 in."],

      avgNoRepaired: ["1  per 8 sq ft"],
      mineralStreaks: ["Yes"],
      barkPockets: ["Few to 1/4 in. x 2 in."],
      wormTracks: ["Yes"],
      vineMarks: ["Yes"],
      crossBars: ["Yes"],
      roughCutRupturedGrain: ["Two 8 in. diameter areas or equivalent"],
      blendedRepairedTaperingHairlineSplits: ["Four 3/16 in. x 8 in."],
      repairs: ["Yes"],
      gumSpots: ["Gum spots and gum streaks in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    D: {
      sapwood: ["Yes"],
      heartwood: ["Yes"],
      colorStreaksOrSpots: ["Yes"],
      colorVariation: ["Yes"],
      sharpColorContrastsAtJoints: ["Yes"],
      bookMatched: ["--"],
      slipMatched: ["--"],
      pleasingMatched: ["--"],
      plainS: ["No Limit"],
      quarRift: ["No Limit"],
      rotary: ["No Limit"],
      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: ["No Limit"],
      conspicuousBurlsMaxSize: ["No Limit"],
      avgNumber: ["No Limit"],
      maxSize: ["No Limit"],
      darkPartTotal: ["No Limit"],
      combinedAvgNumber: ["1 per 3 sq ft 10 per 4 x 8 ft panel"],
      maxSizeSounds: ["1 in."],
      maxSizeRepaired: ["3/4 in."],
      avgNoRepaired: ["1 per 86sq ft"],
      mineralStreaks: ["Yes"],
      barkPockets: ["1/4 in. x 2 in."],
      wormTracks: ["Yes"],
      vineMarks: ["Yes"],
      crossBars: ["Yes"],
      roughCutRupturedGrain: ["1/4 in. x 2 in."],
      blendedRepairedTaperingHairlineSplits: ["Six  1/4 in. x 10 in."],
      repairs: ["Yes"],
      gumSpots: ["Gum spots and gum streaks in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
  },
  walnut: {
    AA: {
      sapwood: ["No"],
      heartwood: ["Yes"],
      colorStreaksOrSpots: ["Slight"],
      colorVariation: ["Slight"],
      sharpColorContrastsAtJoints: ["Yes if Slip, Plank or Random matched	"],
      bookMatched: ["Yes"],
      slipMatched: ["Specify"],
      pleasingMatched: ["--"],
      plainS: ["6 in."],
      quarRift: ["3 in."],
      rotary: ["6 in."],
      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: [
        "1 per 4 sq ft 32 per 4 ft x 8 ft panel",
      ],
      conspicuousBurlsMaxSize: ["1/4 in."],
      avgNumber: ["1 per 5 sq ft 6 per 4 x 8 ft"],
      maxSize: ["1/8 in."],
      darkPartTotal: ["1/4 in."],
      combinedAvgNumber: ["No"],
      maxSizeSounds: ["No"],
      maxSizeRepaired: ["No"],
      avgNoRepaired: ["No"],
      mineralStreaks: ["Slight"],
      barkPockets: ["No"],
      wormTracks: ["No"],
      vineMarks: ["Slight"],
      crossBars: ["Slight"],
      roughCutRupturedGrain: ["No	"],
      blendedRepairedTaperingHairlineSplits: [
        " Two 1/32 in. x 3 in. on panel ends only",
      ],
      repairs: ["Very Small Blending"],
      gumSpots: ["No"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    A: {
      sapwood: ["No^a"],
      heartwood: ["Yes"],
      colorStreaksOrSpots: ["Slight"],
      colorVariation: ["Slight"],
      sharpColorContrastsAtJoints: ["Yes if Slip, Plank or Random matched	"],
      bookMatched: ["Yes"],
      slipMatched: ["Specify"],
      pleasingMatched: ["--"],
      plainS: ["5 in."],
      quarRift: ["3 in."],
      rotary: ["5 in."],

      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: [
        "1 per 1 1/3 sq ft 24 per 4 ft x 8 ft panel",
      ],
      conspicuousBurlsMaxSize: ["3/8 in."],
      avgNumber: ["1 per 2 sq ft 16 per 4 x 8 ft"],
      maxSize: ["1/8 in."],
      darkPartTotal: ["1/4 in."],
      combinedAvgNumber: ["No"],
      maxSizeSounds: ["No"],
      maxSizeRepaired: ["No"],
      avgNoRepaired: ["No"],
      mineralStreaks: ["Slight"],
      barkPockets: ["No"],
      wormTracks: ["No"],
      vineMarks: ["Occasional"],
      crossBars: ["Occasional"],
      roughCutRupturedGrain: ["No	"],
      blendedRepairedTaperingHairlineSplits: ["Two 1/16 in. x 6 in. "],
      repairs: ["Small Blending"],
      gumSpots: ["Occasional Gum spots in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    B: {
      sapwood: ["Yes"],
      heartwood: ["Yes"],
      colorStreaksOrSpots: ["Yes"],
      colorVariation: ["Yes"],
      sharpColorContrastsAtJoints: ["Yes if Slip, Plank or Random matched	"],
      bookMatched: ["Specify"],
      slipMatched: ["Specify"],
      pleasingMatched: ["--"],

      plainS: ["3 in."],
      quarRift: ["3 in."],
      rotary: ["4 in."],

      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: [
        "2 per 1 sq ft 64 per 4 ft x 8 ft panel",
      ],
      conspicuousBurlsMaxSize: ["1/2 in."],
      avgNumber: ["1 per 1 sq ft 32 per 4 x 8 ft"],
      maxSize: ["1/8 in."],
      darkPartTotal: ["1/4 in."],
      combinedAvgNumber: ["1 per 8 sq ft 4 per 4 x 8 ft panel"],

      maxSizeSounds: ["3/8 in."],
      maxSizeRepaired: ["1/8 in."],
      avgNoRepaired: ["1 per 8 sq ft"],
      mineralStreaks: ["Yes"],
      barkPockets: ["Few to 1/8 in. x 1 in. "],
      wormTracks: ["Slight"],
      vineMarks: ["Yes"],
      crossBars: ["Yes"],
      roughCutRupturedGrain: ["Slight"],
      blendedRepairedTaperingHairlineSplits: ["Four 1/8 in. x 8 in."],
      repairs: ["Blending"],
      gumSpots: ["Occasional Gum spots in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    C: {
      sapwood: ["Yes"],
      heartwood: ["Yes"],
      colorStreaksOrSpots: ["Yes"],
      colorVariation: ["Yes"],
      sharpColorContrastsAtJoints: ["Yes"],
      bookMatched: ["--"],
      slipMatched: ["--"],
      pleasingMatched: ["--"],
      plainS: ["No Limit"],
      quarRift: ["No Limit"],
      rotary: ["No Limit"],
      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: ["No Limit"],
      conspicuousBurlsMaxSize: ["No Limit"],
      avgNumber: ["No Limit"],
      maxSize: ["No Limit"],
      darkPartTotal: ["No Limit"],


      combinedAvgNumber: ["1 per 4 sq ft 4 per 4 x 8 ft panel"],
      maxSizeSounds: ["1/2 in."],
      maxSizeRepaired: ["1/2 in."],
      avgNoRepaired: ["1  per 8 sq ft"],
      mineralStreaks: ["Yes"],
      barkPockets: ["Few to 1/4 in. x 2 in."],
      wormTracks: ["Few"],
      vineMarks: ["Yes"],
      crossBars: ["Yes"],
      roughCutRupturedGrain: ["Slight"],
      blendedRepairedTaperingHairlineSplits: ["Four 3/16 in. x 8 in."],
      repairs: ["Yes"],
      gumSpots: ["No"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    D: {
      sapwood: ["Yes"],
      heartwood: ["Yes"],
      colorStreaksOrSpots: ["Yes"],
      colorVariation: ["Yes"],
      sharpColorContrastsAtJoints: ["Yes"],
      bookMatched: ["--"],
      slipMatched: ["--"],
      pleasingMatched: ["--"],
      plainS: ["No Limit"],
      quarRift: ["No Limit"],
      rotary: ["No Limit"],
      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: ["No Limit"],
      conspicuousBurlsMaxSize: ["No Limit"],
      avgNumber: ["No Limit"],
      maxSize: ["No Limit"],
      darkPartTotal: ["No Limit"],
      combinedAvgNumber: ["1 per 3 sq ft 10 per 4 x 8 ft panel"],
      maxSizeSounds: ["1 in."],
      maxSizeRepaired: ["3/4 in."],
      avgNoRepaired: ["1 per 6 sq ft"],
      mineralStreaks: ["Yes"],
      barkPockets: ["1/4 in. x 2 in."],
      wormTracks: ["Yes"],
      vineMarks: ["Yes"],
      crossBars: ["Yes"],
      roughCutRupturedGrain: ["Two 8 in. dia. areas or equivalent"],
      blendedRepairedTaperingHairlineSplits: ["Six  1/4 in. x 10 in."],
      repairs: ["Yes"],
      gumSpots: ["No"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
  },
  white_oak: {
    AA: {
      sapwood: ["No"],
      heartwood: ["Yes"],
      colorStreaksOrSpots: ["Yes"],
      colorVariation: ["Slight"],
      sharpColorContrastsAtJoints: ["Yes if Slip, Plank or Random matched	"],
      bookMatched: ["Yes"],
      slipMatched: ["Specify"],
      pleasingMatched: ["--"],
      plainS: ["6 in."],
      quarRift: ["3 in."],
      rotary: ["6 in."],
      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: [
        "1 per 4 sq ft 8 per 4 ft x 8 ft panel",
      ],
      conspicuousBurlsMaxSize: ["1/4 in."],
      avgNumber: ["No"],
      maxSize: ["No"],
      darkPartTotal: ["No"],

      combinedAvgNumber: ["No"],
      maxSizeSounds: ["No"],
      maxSizeRepaired: ["No"],
      avgNoRepaired: ["No"],
      mineralStreaks: ["No"],
      barkPockets: ["No"],
      wormTracks: ["No"],
      vineMarks: ["No"],
      crossBars: ["Slight"],
      roughCutRupturedGrain: ["No	"],
      blendedRepairedTaperingHairlineSplits: [
        " Two 1/32 in. x 3 in. on panel ends only",
      ],
      repairs: ["Very Small Blending"],
      gumSpots: [""],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    A: {
      sapwood: ["Yes^a"],
      heartwood: ["Yes"],
      colorStreaksOrSpots: ["Yes"],
      colorVariation: ["Slight"],
      sharpColorContrastsAtJoints: ["Yes if Slip, Plank or Random matched	"],
      bookMatched: ["Yes"],
      slipMatched: ["Specify"],
      pleasingMatched: ["--"],
      plainS: ["5 in."],
      quarRift: ["3 in."],
      rotary: ["5 in."],

      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: [
        "1 per 2 2/3 sq ft 12 per 4 ft x 8 ft panel",
      ],
      conspicuousBurlsMaxSize: ["3/8 in."],
      avgNumber: ["1 per 3 sq ft 10 per 4 x 8 ft panel"],
      maxSize: ["1/8 in."],
      darkPartTotal: ["1/4 in."],
      combinedAvgNumber: ["No"],
      maxSizeSounds: ["No"],
      maxSizeRepaired: ["No"],
      avgNoRepaired: ["No"],
      mineralStreaks: ["Slight, Blending"],
      barkPockets: ["No"],
      wormTracks: ["No"],
      vineMarks: ["Slight"],
      crossBars: ["Slight"],
      roughCutRupturedGrain: ["No	"],
      blendedRepairedTaperingHairlineSplits: ["Two 1/16 in. x 6 in."],
      repairs: ["Slight, Blending"],
      gumSpots: [""],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    B: {
      sapwood: ["Yes"],
      heartwood: ["Yes"],
      colorStreaksOrSpots: ["Yes"],
      colorVariation: ["Yes"],
      sharpColorContrastsAtJoints: ["Yes if Slip, Plank or Random matched	"],
      bookMatched: ["Specify"],
      slipMatched: ["Specify"],
      pleasingMatched: ["--"],
      plainS: ["3 in."],
      quarRift: ["3 in."],
      rotary: ["4 in."],

      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: [
        "1 per 1 1/3 sq ft 24 per 4 ft x 8 ft panel",
      ],
      conspicuousBurlsMaxSize: ["1/2 in."],
      avgNumber: ["1 per 2 sq ft 16 per 3 x 8 ft panel"],
      maxSize: ["1/8 in."],
      darkPartTotal: ["1/4 in."],

      combinedAvgNumber: ["1 per 8 sq ft 4 per 4 x 8 ft panel"],
      maxSizeSounds: ["3/8 in."],
      maxSizeRepaired: ["1/8 in."],
      avgNoRepaired: ["1 per 8 sq ft"],
      mineralStreaks: ["Few to 12 in."],
      barkPockets: ["Few to 1/8 in. x 1 in. "],
      wormTracks: ["Slight"],
      vineMarks: ["Yes"],
      crossBars: ["Yes"],
      roughCutRupturedGrain: ["Slight"],
      blendedRepairedTaperingHairlineSplits: ["Four 1/8 in. x 8 in."],
      repairs: ["Blending"],
      gumSpots: ["Occasional Gum spots in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    C: {
      sapwood: ["Yes"],
      heartwood: ["Yes"],
      colorStreaksOrSpots: ["Yes"],
      colorVariation: ["Yes"],
      sharpColorContrastsAtJoints: ["Yes"],
      bookMatched: ["--"],
      slipMatched: ["--"],
      pleasingMatched: ["--"],
      plainS: ["No Limit"],
      quarRift: ["No Limit"],
      rotary: ["No Limit"],
      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: ["No Limit"],
      conspicuousBurlsMaxSize: ["No Limit"],
      avgNumber: ["No Limit"],
      maxSize: ["No Limit"],
      darkPartTotal: ["No Limit"],
      combinedAvgNumber: ["1 per 4 sq ft 4 per 4 x 8 ft panel"],
      maxSizeSounds: ["1/2 in."],
      maxSizeRepaired: ["1/2 in."],

      avgNoRepaired: ["1  per 8 sq ft"],
      mineralStreaks: ["Yes"],
      barkPockets: ["Few to 1/4 in. x 2 in."],
      wormTracks: ["Few"],
      vineMarks: ["Yes"],
      crossBars: ["Yes"],
      roughCutRupturedGrain: ["Slight"],
      blendedRepairedTaperingHairlineSplits: ["Four 3/16 in. x 8 in."],
      repairs: ["Yes"],
      gumSpots: ["No"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
    D: {
      sapwood: ["Yes"],
      heartwood: ["Yes"],
      colorStreaksOrSpots: ["Yes"],
      colorVariation: ["Yes"],
      sharpColorContrastsAtJoints: ["Yes"],
      bookMatched: ["--"],
      slipMatched: ["--"],
      pleasingMatched: ["--"],
      plainS: ["No Limit"],
      quarRift: ["No Limit"],
      rotary: ["No Limit"],
      smallConspicuousBurlsAndPinKnotsCombinedAvgNumber: ["No Limit"],
      conspicuousBurlsMaxSize: ["No Limit"],
      avgNumber: ["No Limit"],
      maxSize: ["No Limit"],
      darkPartTotal: ["No Limit"],
      combinedAvgNumber: ["1 per 3 sq ft 10 per 4 x 8 ft panel"],
      maxSizeSounds: ["1 in."],
      maxSizeRepaired: ["3/4 in."],
      avgNoRepaired: ["1 per 86sq ft"],
      mineralStreaks: ["Yes"],
      barkPockets: ["1/4 in. x 2 in."],
      wormTracks: ["Yes"],
      vineMarks: ["Yes"],
      crossBars: ["Yes"],
      roughCutRupturedGrain: ["1/4 in. x 2 in."],
      blendedRepairedTaperingHairlineSplits: ["Six  1/4 in. x 10 in."],
      repairs: ["Yes"],
      gumSpots: ["Gum spots and gum streaks in Cherry"],
      quartered: [
        "1 inch in 12 inches maximum grain slope, 2 1/2 inches in 12 inches maximum grain sweep",
      ],
    },
  },
};
export const getData = (Specie: keyof Data, grade: keyof Grades) => {
  const specieKey = Specie.split(" ").join("_") as keyof Data; // Type assertion
  return data[specieKey][grade];
};


